_format_version: "1.1"

services:
  - name: auth-v1
    url: http://auth:8081/
    routes:
      - name: auth-v1-route
        strip_path: true
        paths:
          - /auth/v1/
    plugins:
      - name: cors
